doctrine:
    orm:
        resolve_target_entities:
            TechPromux\Bundle\BaseBundle\Entity\Owner\ResourceOwner: TechPromux\Bundle\BaseBundle\Entity\Owner\DefaultUser\DefaultUserResourceOwner

