services:
#    tech_promux_core.example:
#        class:  TechPromux\BaseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # Manager Services

    techpromux_base.manager.default_user_security:
        class:  TechPromux\BaseBundle\Manager\Security\DefaultUser\DefaultSecurityManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setSecurityTokenStorage,['@security.token_storage']]
            - [ setSecurityAuthorizationChecker,['@security.authorization_checker']]
            - [ setUserManager,['@fos_user.user_manager']]
            - [ setGroupManager,['@fos_user.group_manager']]
            - [ setSecretAppString,['%secret%']]

    techpromux.manager.default_security:
        alias: techpromux_base.manager.default_user_security


    techpromux_base.manager.default_user_resource_owner:
        class:  TechPromux\BaseBundle\Manager\Owner\DefaultUser\DefaultUserResourceOwnerManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setSecurityManager,['@techpromux.manager.default_security']]

    techpromux.manager.default_resource_owner:
        alias: techpromux_base.manager.default_user_resource_owner
