services:
#    tech_promux_core.example:
#        class:  TechPromux\BaseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # Alias Services

    techpromux.manager.default_security:
        alias: techpromux_base.manager.default_security

    techpromux.manager.default_resource_context:
        alias: techpromux_base.manager.default_resource_context

    # Manager Services

    techpromux_base.manager.default_security:
        class:  TechPromux\BaseBundle\Manager\Security\DefaultSecurityManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setSecretAppString,['%secret%']]
            - [ setSecurityTokenStorage,['@security.token_storage']]
            - [ setSecurityAuthorizationChecker,['@security.authorization_checker']]

    techpromux_base.manager.default_resource_context:
        class:  TechPromux\BaseBundle\Manager\Context\DefaultResourceContextManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]

    techpromux_base.manager.default_resource_context_by_user:
        class:  TechPromux\BaseBundle\Manager\Context\DefaultResourceContextByUserManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setSecurityManager,['@techpromux.manager.default_security']]
